sudo: required

language: c

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh

os:
  - linux

env:
  - OCAML_VERSION=4.07

matrix:
  allow_failures:
    - os: osx
      env: OCAML_VERSION=4.07

script:
  - sudo apt-get update -qq ;
    sudo apt-get install -y -qq protobuf-compiler ;
    bash -ex .travis-ocaml.sh ;
    export OPAMYES=1 ;
    eval $(opam config env) ;
    opam pin add geneweb.dev git://github.com/geneanet/geneweb.git#next --no-action ;
    opam pin add jingoo.dev git://github.com/geneanet/jingoo.git#next --no-action ;
    opam pin add gwd . --no-action ;
    opam install gwd --deps-only ;
    make ;

notifications:
  email:
    recipients:
      - julien.sagot@geneanet.org
    on_success: always
    on_failure: always

after_failure:
  - cat ~/.opam/log/*.out
