sudo: required

language: c

install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh

os:
  - linux
  - osx

env:
  - OCAML_VERSION=4.05
  - OCAML_VERSION=4.06
  - OCAML_VERSION=4.07

matrix:
  allow_failures:
    - os: osx
      env: OCAML_VERSION=4.07

script:
  - bash -ex .travis-ocaml.sh ;
    export OPAMYES=1 ;
    eval $(opam config env) ;
    opam pin add gwd . --no-action ;
    opam install gwd --deps-only ;
    make ;

notifications:
  email:
    recipients:
      - julien.sagot@geneanet.org
    on_success: always
    on_failure: always

after_failure:
  - cat ~/.opam/log/*.out
